// Writes the reference table StateRegistryTest checks Warp's packet ids against: the id of every
// packet, in every state and direction, at each protocol Warp registers, from the pinned
// minecraft-data. Run it (`npm run packet-ids` in e2e/) after adding a protocol to
// ProtocolVersion.java or bumping minecraft-data.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';

import { E2E_DIR } from '../src/versions.js';

const require = createRequire(import.meta.url);
const mcData = require('minecraft-data');
const { version: mcDataVersion } = require('minecraft-data/package.json');

const ROOT = join(E2E_DIR, '..');
const PROTOCOL_VERSION = join(ROOT, 'protocol/src/main/java/dev/warp/protocol/ProtocolVersion.java');
const TABLE = join(ROOT, 'protocol/src/test/resources/dev/warp/protocol/packet/packet-ids.txt');

/** minecraft-data's state and direction names, in Warp's terms and order. */
const STATES = { handshaking: 'handshake', status: 'status', login: 'login', configuration: 'configuration', play: 'play' };
const DIRECTIONS = { toServer: 'serverbound', toClient: 'clientbound' };

/** The distinct protocol numbers Warp registers, ascending. */
function warpProtocols() {
  const source = readFileSync(PROTOCOL_VERSION, 'utf8');
  const protocols = [...source.matchAll(/register\((\d+), "[^"]+"\)/g)].map((m) => Number(m[1]));
  return [...new Set(protocols)].sort((a, b) => a - b);
}

/**
 * minecraft-data's definition of exactly this protocol, or null. The library resolves a version it
 * has no data for to a neighbouring one, so the resolved protocol number is checked.
 */
function protocolData(protocol) {
  const isRelease = (v) => Number(/^\d+(\.\d+)*$/.test(v.minecraftVersion));
  const candidates = [...(mcData.postNettyVersionsByProtocolVersion.pc[protocol] ?? [])];
  for (const candidate of candidates.sort((a, b) => isRelease(b) - isRelease(a))) {
    const data = mcData(candidate.minecraftVersion);
    if (data?.protocol && data.version.version === protocol) return data.protocol;
  }
  return null;
}

/** [packet name, id] pairs of one state and direction of a protocol definition. */
function packetIds(definition) {
  const mappings = definition?.types?.packet?.[1]?.[0]?.type?.[1]?.mappings ?? {};
  return Object.entries(mappings).map(([id, name]) => [name, Number.parseInt(id, 16)]);
}

const hex = (id) => `0x${id.toString(16).toUpperCase().padStart(2, '0')}`;

const checked = [];
const unchecked = [];
// "state direction" → (packet name → (protocol → id)), in Warp's state and direction order.
const registries = new Map(
  Object.values(STATES).flatMap((s) => Object.values(DIRECTIONS).map((d) => [`${s} ${d}`, new Map()])),
);
for (const protocol of warpProtocols()) {
  const data = protocolData(protocol);
  if (!data) {
    unchecked.push(protocol);
    continue;
  }
  checked.push(protocol);
  for (const [mcState, state] of Object.entries(STATES)) {
    for (const [mcDirection, direction] of Object.entries(DIRECTIONS)) {
      const packets = registries.get(`${state} ${direction}`);
      for (const [name, id] of packetIds(data[mcState]?.[mcDirection])) {
        if (!packets.has(name)) packets.set(name, new Map());
        packets.get(name).set(protocol, id);
      }
    }
  }
}

const rows = [];
for (const [registry, packets] of registries) {
  for (const name of [...packets.keys()].sort()) {
    const ids = packets.get(name);
    const changes = [];
    let previous = '-';
    for (const protocol of checked) {
      const id = ids.has(protocol) ? hex(ids.get(protocol)) : '-';
      if (id !== previous) changes.push(`${id}@${protocol}`);
      previous = id;
    }
    rows.push(`${registry} ${name} ${changes.join(' ')}`);
  }
}

const header = [
  `# Packet ids of every protocol Warp registers, from minecraft-data ${mcDataVersion}.`,
  '# Generated by e2e/tools/packet-ids.js (npm run packet-ids): regenerate it, do not edit it.',
  '#',
  '# "checked": the protocols minecraft-data has data for; "unchecked": those it has none for.',
  '# Then one line per packet: state, direction, minecraft-data name, and the id the packet takes',
  '# from each protocol on ("-": absent from that protocol on).',
  ['checked', ...checked].join(' '),
  ['unchecked', ...unchecked].join(' '),
];
writeFileSync(TABLE, `${[...header, ...rows].join('\n')}\n`);
console.log(`wrote ${TABLE}: ${rows.length} packets at ${checked.length} protocols`);
