// A Warp instance under test: its own directory, generated warp.conf, private copy of the jar.
import { randomUUID } from 'node:crypto';
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { ManagedProcess, run } from './proc.js';

/**
 * Warp output lines that fail a run: anything logged at ERROR or FATAL, Netty buffer leaks,
 * uncaught exceptions printed by the JVM itself, JVM crashes, keep-alive trouble (bots always echo
 * the keep-alive id they received, at once, so a mismatch or a time-out is a proxy bug) and read
 * time-outs (Warp logs them at INFO, as a player who goes quiet is routine; bots and backends here
 * never do, so one is a hang somewhere between them).
 */
export const WARP_FAILURES = [
  /^\S+ \S+ \[[^\]]*\] (ERROR|FATAL) /,
  /LEAK: /,
  /^Exception in thread /,
  /^# A fatal error has been detected by the Java Runtime Environment/,
  /Invalid KeepAlive ID from player /,
  /timed out \(no KeepAlive response/,
  /Connection \S+ timed out in \S+: the (client|backend) sent nothing/,
];

/** Where the harness's stand-in for Mojang's key goes, in Warp's working directory. */
const SIGNER_FILE = 'profile-key-signer.pem';

export class Warp {
  /**
   * @param {object} options
   * @param {string} options.name instance label ("warp", "warp-alt")
   * @param {string} options.dir working directory (wiped)
   * @param {string} options.jar Warp shadow jar (copied: a rebuild never touches a running JVM)
   * @param {string} options.java Java 25 executable
   * @param {number} options.port
   * @param {boolean} options.online online mode against the mock session server
   * @param {string|null} options.sessionServer `hasJoined` URL of the mock session server
   * @param {string|null} options.profileKeySigner PEM public key Warp trusts to sign 1.19 to 1.19.2
   *   profile keys instead of Mojang's (the harness signs its bots' keys)
   * @param {boolean} options.passthrough `compression.passthrough`
   * @param {number} options.threshold `compression.threshold`
   * @param {Record<string, number>} options.servers name → port of each backend
   * @param {string[]} options.fallbackOrder first entry is the default server
   * @param {string} options.logDir
   * @param {string[]} [options.jvmArgs] JVM options after the defaults (the last -Xmx wins)
   */
  constructor(options) {
    Object.assign(this, options);
    this.process = null;
  }

  prepare() {
    rmSync(this.dir, { recursive: true, force: true });
    mkdirSync(this.dir, { recursive: true });
    copyFileSync(this.jar, join(this.dir, 'warp.jar'));
    writeFileSync(join(this.dir, 'warp.conf'), this.config());
    if (this.profileKeySigner) writeFileSync(join(this.dir, SIGNER_FILE), this.profileKeySigner);
  }

  config() {
    const servers = Object.entries(this.servers)
      .map(([name, port]) => `  ${name} {\n    address = "127.0.0.1:${port}"\n  }`)
      .join('\n');
    return `# Generated by e2e/src/warp.js
bind = "127.0.0.1:${this.port}"
online-mode = ${this.online}
servers {
${servers}
}
default-server = "${this.fallbackOrder[0]}"
fallback-order = [${this.fallbackOrder.map((s) => `"${s}"`).join(', ')}]
forwarding {
  mode = "none"
}
compression {
  threshold = ${this.threshold}
  level = -1
  passthrough = ${this.passthrough}
}
`;
  }

  start() {
    const args = [
      '-Xms256m',
      '-Xmx512m',
      '--sun-misc-unsafe-memory-access=allow',
      // Every ByteBuf is tracked: a buffer the proxy forgets to release is reported as an ERROR.
      '-Dio.netty.leakDetection.level=paranoid',
      ...(this.jvmArgs ?? []),
      ...(this.online ? [`-Dmojang.sessionserver=${this.sessionServer}`] : []),
      ...(this.profileKeySigner ? [`-Dwarp.profilekeys.signer=${SIGNER_FILE}`] : []),
      '-jar',
      'warp.jar',
    ];
    this.process = new ManagedProcess(this.name, this.java, args, {
      cwd: this.dir,
      logFile: join(this.logDir, `${this.name}.log`),
      failures: WARP_FAILURES,
    }).start();
    return this.process.waitFor(/Warp is listening/, 60_000);
  }

  /**
   * Forces a full GC so that leaked buffers become unreachable; Netty reports them the next time it
   * allocates, so the caller should generate a little traffic afterwards.
   */
  async collectGarbage() {
    if (!this.process?.alive) return;
    await this.jcmd(['GC.run']).catch(() => {});
  }

  /** Runs diagnostic commands (`GC.heap_info`, `VM.native_memory summary`…) in one jcmd call. */
  async jcmd(commands) {
    const file = join(this.dir, `jcmd-${randomUUID()}.txt`);
    writeFileSync(file, `${commands.join('\n')}\n`);
    try {
      return await run(jcmd(this.java), [String(this.process.pid), '-f', file]);
    } finally {
      rmSync(file, { force: true });
    }
  }

  /** Stops the instance. A shutdown that hangs is a bug: the thread dump goes to the log. */
  async stop() {
    if (!this.process) return null;
    const result = await this.process.stop({
      graceMs: 20_000,
      beforeKill: async (p) => {
        const dump = await run(jcmd(this.java), [String(p.pid), 'Thread.print']).catch((e) => String(e));
        writeFileSync(join(this.logDir, `${this.name}-hung-shutdown-threads.txt`), dump);
      },
    });
    return result;
  }

  failures() {
    return this.process?.failures() ?? [];
  }
}

function jcmd(java) {
  return join(dirname(java), 'jcmd');
}
