import net.ltgt.gradle.errorprone.errorprone

// JMH micro-benchmarks. Sources live in src/jmh/java and are never part of the shipped artifacts.
//
//   ./gradlew :protocol:jmh                                  # run every benchmark
//   ./gradlew :protocol:jmh -Pjmh.includes=ForwardingPath    # run benchmarks matching a regex
//
// Results are written as JSON to build/results/jmh/results.json for archiving and comparison.
// Iteration, fork and warmup settings belong on AbstractMicrobenchmark, which every benchmark
// extends, so that they all share one documented methodology.

plugins {
    id("me.champeau.jmh")
}

val libs = the<VersionCatalogsExtension>().named("libs")

jmh {
    jmhVersion = libs.findVersion("jmh").get().requiredVersion
    includes.addAll(providers.gradleProperty("jmh.includes").map { listOf(it) }.orElse(listOf()))
    profilers.add("gc")
    resultFormat = "JSON"
    resultsFile = layout.buildDirectory.file("results/jmh/results.json")
    failOnError = true
}

// The java executable of the toolchain that compiles the benchmarks, for scripts that run the
// benchmark jar themselves (bin/bench-guard.sh): Gradle resolves it the same way on every machine.
val toolchainJava = the<JavaToolchainService>()
    .launcherFor(the<JavaPluginExtension>().toolchain)
    .map { it.executablePath.asFile.absolutePath }
tasks.register("jmhJava") {
    group = "jmh"
    description = "Prints the path of the java executable of the benchmarks' toolchain."
    val executable = toolchainJava // a local: the action must not capture the build script
    doLast { println(executable.get()) }
}

// JMH @State fields are initialized in @Setup methods or injected (@Param), not in constructors.
tasks.named<JavaCompile>("compileJmhJava") {
    options.errorprone {
        option("NullAway:CustomInitializerAnnotations", "org.openjdk.jmh.annotations.Setup")
        option("NullAway:ExcludedFieldAnnotations", "org.openjdk.jmh.annotations.Param")
    }
}

// Code generated by the JMH annotation processor is not ours to lint.
tasks.named<JavaCompile>("jmhCompileGeneratedClasses") {
    options.errorprone.enabled = false
}
